const { createClient } = require('@supabase/supabase-js');
require('dotenv').config({ path: '.env.local' });

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseKey) {
  console.error('Missing NEXT_PUBLIC_SUPABASE_URL or NEXT_PUBLIC_SUPABASE_ANON_KEY.');
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey);

const now = new Date();
const daysAgo = (d) => new Date(now.getTime() - d * 86400000).toISOString();
const hoursAgo = (h) => new Date(now.getTime() - h * 3600000).toISOString();
const hoursFromNow = (h) => new Date(now.getTime() + h * 3600000).toISOString();

const ids = {
  donors: {
    koramangala: '11111111-1111-1111-1111-111111111111',
    indiranagar: '11111111-1111-1111-1111-111111111112',
    jayanagar: '11111111-1111-1111-1111-111111111113',
    whitefield: '11111111-1111-1111-1111-111111111114',
    hsr: '11111111-1111-1111-1111-111111111115',
    mgRoad: '11111111-1111-1111-1111-111111111116',
    electronicCity: '11111111-1111-1111-1111-111111111117',
    malleshwaram: '11111111-1111-1111-1111-111111111118',
    jpNagar: '11111111-1111-1111-1111-111111111119',
    marathahalli: '11111111-1111-1111-1111-111111111120',
    hebbal: '11111111-1111-1111-1111-111111111121',
  },
  ngos: {
    reliefTrust: '22222222-2222-2222-2222-222222222222',
    helpingHands: '33333333-3333-3333-3333-333333333333',
    communityMeals: '22222222-2222-2222-2222-222222222223',
    hopeShelter: '22222222-2222-2222-2222-222222222224',
    annadaan: '22222222-2222-2222-2222-222222222225',
  },
  delivery: '44444444-4444-4444-4444-444444444444',
  deliveryBackup: '44444444-4444-4444-4444-444444444445',
};

const demoUserIds = [
  ...Object.values(ids.donors),
  ...Object.values(ids.ngos),
  ids.delivery,
  ids.deliveryBackup,
];

const legacyDemoUserIds = [
  'user-donor-1',
  'user-ngo-1',
  'user-ngo-2',
  'user-delivery-1',
];

const demoDonationOwnerIds = [...demoUserIds, ...legacyDemoUserIds];

const donationIds = {
  vegBiryani: 'aaaa1111-1111-1111-1111-111111111111',
  pastries: 'bbbb2222-2222-2222-2222-222222222222',
  fruitCups: 'cccc3333-3333-3333-3333-333333333333',
  lunchPacks: 'dddd4444-4444-4444-4444-444444444444',
  juiceBottles: 'aaaa1111-2222-3333-4444-555555555555',
  paneer: 'bbbb2222-3333-4444-5555-666666666666',
  sandwiches: 'cccc3333-4444-5555-6666-777777777777',
  idliVada: 'dddd4444-5555-6666-7777-888888888888',
  cancelled: 'eeee5555-6666-7777-8888-999999999999',
  templeMeals: 'aaaa2222-2222-2222-2222-222222222222',
  snackBoxes: 'bbbb3333-3333-3333-3333-333333333333',
  dinnerTrays: 'cccc4444-4444-4444-4444-444444444444',
  breadLoaves: 'dddd5555-5555-5555-5555-555555555555',
  dosaPacks: 'eeee6666-6666-6666-6666-666666666666',
  coffeeFlasks: 'ffff7777-7777-7777-7777-777777777777',
};

const jobIds = {
  lunchPacks: 'eeee5555-5555-5555-5555-555555555555',
  juiceBottles: 'ffff6666-6666-6666-6666-666666666666',
  paneer: '77777777-7777-7777-7777-777777777777',
  sandwiches: '88888888-8888-8888-8888-888888888888',
  dinnerTrays: '99999999-9999-9999-9999-999999999999',
  dosaPacks: 'aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee',
};

const samplePhotos = {
  biryani: 'https://images.unsplash.com/photo-1563379091339-03246963d7d9?auto=format&fit=crop&w=900&q=80',
  pastries: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=900&q=80',
  fruit: 'https://images.unsplash.com/photo-1490474418585-ba9bad8fd0ea?auto=format&fit=crop&w=900&q=80',
  lunch: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=900&q=80',
  sandwiches: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=900&q=80',
  breakfast: 'https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?auto=format&fit=crop&w=900&q=80',
  beverages: 'https://images.unsplash.com/photo-1622597467836-f3285f2131b8?auto=format&fit=crop&w=900&q=80',
};

const seedUsers = [
  {
    id: ids.donors.koramangala,
    name: 'Asha Rao',
    email: 'donor@sharebite.demo',
    password: 'demo123',
    role: 'donor',
    organization_name: 'Koramangala Kitchen',
    phone: '+91 98765 43001',
    area: 'Koramangala, Bangalore',
    created_at: '2025-11-15T09:00:00Z',
  },
  {
    id: ids.donors.indiranagar,
    name: 'Nikhil Verma',
    email: 'donor-indiranagar@sharebite.demo',
    password: 'demo123',
    role: 'donor',
    organization_name: 'Indiranagar Bakery House',
    phone: '+91 98765 43002',
    area: 'Indiranagar, Bangalore',
    created_at: '2025-11-16T09:00:00Z',
  },
  {
    id: ids.donors.jayanagar,
    name: 'Meera Iyer',
    email: 'donor-jayanagar@sharebite.demo',
    password: 'demo123',
    role: 'donor',
    organization_name: 'Jayanagar Event Caterers',
    phone: '+91 98765 43003',
    area: 'Jayanagar, Bangalore',
    created_at: '2025-11-17T09:00:00Z',
  },
  {
    id: ids.donors.whitefield,
    name: 'Arjun Nair',
    email: 'donor-whitefield@sharebite.demo',
    password: 'demo123',
    role: 'donor',
    organization_name: 'Whitefield Tech Park Canteen',
    phone: '+91 98765 43004',
    area: 'Whitefield, Bangalore',
    created_at: '2025-11-18T09:00:00Z',
  },
  {
    id: ids.donors.hsr,
    name: 'Divya Prasad',
    email: 'donor-hsr@sharebite.demo',
    password: 'demo123',
    role: 'donor',
    organization_name: 'HSR Fresh Foods',
    phone: '+91 98765 43005',
    area: 'HSR Layout, Bangalore',
    created_at: '2025-11-19T09:00:00Z',
  },
  {
    id: ids.donors.mgRoad,
    name: 'Rohan Kapoor',
    email: 'donor-mgroad@sharebite.demo',
    password: 'demo123',
    role: 'donor',
    organization_name: 'MG Road Cafe',
    phone: '+91 98765 43006',
    area: 'MG Road, Bangalore',
    created_at: '2025-11-20T09:00:00Z',
  },
  {
    id: ids.donors.electronicCity,
    name: 'Kavya Suresh',
    email: 'donor-electronic-city@sharebite.demo',
    password: 'demo123',
    role: 'donor',
    organization_name: 'Electronic City Corporate Kitchen',
    phone: '+91 98765 43007',
    area: 'Electronic City, Bangalore',
    created_at: '2025-11-21T09:00:00Z',
  },
  {
    id: ids.donors.malleshwaram,
    name: 'Srinivas Murthy',
    email: 'donor-malleshwaram@sharebite.demo',
    password: 'demo123',
    role: 'donor',
    organization_name: 'Malleshwaram Tiffin Centre',
    phone: '+91 98765 43008',
    area: 'Malleshwaram, Bangalore',
    created_at: '2025-11-22T09:00:00Z',
  },
  {
    id: ids.donors.jpNagar,
    name: 'Pooja Shetty',
    email: 'donor-jpnagar@sharebite.demo',
    password: 'demo123',
    role: 'donor',
    organization_name: 'JP Nagar Community Kitchen',
    phone: '+91 98765 43009',
    area: 'JP Nagar, Bangalore',
    created_at: '2025-11-23T09:00:00Z',
  },
  {
    id: ids.donors.marathahalli,
    name: 'Kiran Bhat',
    email: 'donor-marathahalli@sharebite.demo',
    password: 'demo123',
    role: 'donor',
    organization_name: 'Marathahalli Office Pantry',
    phone: '+91 98765 43010',
    area: 'Marathahalli, Bangalore',
    created_at: '2025-11-24T09:00:00Z',
  },
  {
    id: ids.donors.hebbal,
    name: 'Zoya Ahmed',
    email: 'donor-hebbal@sharebite.demo',
    password: 'demo123',
    role: 'donor',
    organization_name: 'Hebbal Hostel Mess',
    phone: '+91 98765 43011',
    area: 'Hebbal, Bangalore',
    created_at: '2025-11-25T09:00:00Z',
  },
  {
    id: ids.ngos.reliefTrust,
    name: 'Priya Menon',
    email: 'ngo@sharebite.demo',
    password: 'demo123',
    role: 'ngo',
    organization_name: 'Bengaluru Food Relief Trust',
    phone: '+91 98765 43101',
    area: 'JP Nagar, Bangalore',
    created_at: '2025-10-01T09:00:00Z',
  },
  {
    id: ids.ngos.helpingHands,
    name: 'Ananya Reddy',
    email: 'ngo2@sharebite.demo',
    password: 'demo123',
    role: 'ngo',
    organization_name: 'Helping Hands Bangalore',
    phone: '+91 98765 43102',
    area: 'HSR Layout, Bangalore',
    created_at: '2025-10-10T09:00:00Z',
  },
  {
    id: ids.ngos.communityMeals,
    name: 'Sanjay Kulkarni',
    email: 'ngo-community@sharebite.demo',
    password: 'demo123',
    role: 'ngo',
    organization_name: 'Community Meals Foundation',
    phone: '+91 98765 43103',
    area: 'Marathahalli, Bangalore',
    created_at: '2025-10-11T09:00:00Z',
  },
  {
    id: ids.ngos.hopeShelter,
    name: 'Farah Khan',
    email: 'ngo-hope@sharebite.demo',
    password: 'demo123',
    role: 'ngo',
    organization_name: 'Hope Shelter Network',
    phone: '+91 98765 43104',
    area: 'Hebbal, Bangalore',
    created_at: '2025-10-12T09:00:00Z',
  },
  {
    id: ids.ngos.annadaan,
    name: 'Ravi Gowda',
    email: 'ngo-annadaan@sharebite.demo',
    password: 'demo123',
    role: 'ngo',
    organization_name: 'Annadaan Bengaluru',
    phone: '+91 98765 43105',
    area: 'Jayanagar, Bangalore',
    created_at: '2025-10-13T09:00:00Z',
  },
  {
    id: ids.delivery,
    name: 'Vikram Das',
    email: 'delivery@sharebite.demo',
    password: 'demo123',
    role: 'delivery',
    organization_name: 'Bangalore Delivery Collective',
    phone: '+91 98765 43201',
    area: 'MG Road, Bangalore',
    created_at: '2025-11-01T09:00:00Z',
  },
  {
    id: ids.deliveryBackup,
    name: 'Neha Patil',
    email: 'delivery-backup@sharebite.demo',
    password: 'demo123',
    role: 'delivery',
    organization_name: 'Bangalore Delivery Collective',
    phone: '+91 98765 43202',
    area: 'Indiranagar, Bangalore',
    created_at: '2025-11-02T09:00:00Z',
  },
];

const seedNGOProfiles = [
  {
    id: '11111111-2222-1111-1111-111111111111',
    user_id: ids.ngos.reliefTrust,
    name: 'Bengaluru Food Relief Trust',
    supported_food_types: JSON.stringify(['cooked_meals', 'bakery', 'fresh_produce', 'packaged', 'beverages']),
    max_daily_capacity: 240,
    area: 'JP Nagar, Bangalore',
    latitude: 12.9063,
    longitude: 77.5857,
    acceptance_rate: 0.94,
    active_status: true,
  },
  {
    id: '22222222-3333-1111-1111-111111111111',
    user_id: ids.ngos.helpingHands,
    name: 'Helping Hands Bangalore',
    supported_food_types: JSON.stringify(['cooked_meals', 'fresh_produce', 'bakery']),
    max_daily_capacity: 140,
    area: 'HSR Layout, Bangalore',
    latitude: 12.9121,
    longitude: 77.6446,
    acceptance_rate: 0.88,
    active_status: true,
  },
  {
    id: '33333333-4444-1111-1111-111111111111',
    user_id: ids.ngos.communityMeals,
    name: 'Community Meals Foundation',
    supported_food_types: JSON.stringify(['cooked_meals', 'packaged', 'beverages']),
    max_daily_capacity: 180,
    area: 'Marathahalli, Bangalore',
    latitude: 12.9569,
    longitude: 77.7011,
    acceptance_rate: 0.86,
    active_status: true,
  },
  {
    id: '44444444-5555-1111-1111-111111111111',
    user_id: ids.ngos.hopeShelter,
    name: 'Hope Shelter Network',
    supported_food_types: JSON.stringify(['cooked_meals', 'fresh_produce', 'dairy', 'packaged']),
    max_daily_capacity: 120,
    area: 'Hebbal, Bangalore',
    latitude: 13.0358,
    longitude: 77.5970,
    acceptance_rate: 0.81,
    active_status: true,
  },
  {
    id: '55555555-6666-1111-1111-111111111111',
    user_id: ids.ngos.annadaan,
    name: 'Annadaan Bengaluru',
    supported_food_types: JSON.stringify(['cooked_meals', 'bakery', 'fresh_produce', 'beverages']),
    max_daily_capacity: 160,
    area: 'Jayanagar, Bangalore',
    latitude: 12.9250,
    longitude: 77.5938,
    acceptance_rate: 0.9,
    active_status: true,
  },
];

const seedDonations = [
  {
    id: donationIds.vegBiryani,
    donor_id: ids.donors.koramangala,
    title: '35 Veg Biryani Meal Boxes',
    category: 'cooked_meals',
    food_type: 'Veg biryani',
    quantity: 35,
    unit: 'boxes',
    urgency: 'high',
    prepared_at: hoursAgo(1.5),
    expires_at: hoursFromNow(3),
    pickup_start: hoursFromNow(0.25),
    pickup_end: hoursFromNow(1.5),
    location_name: 'Koramangala Kitchen, 4th Block, Koramangala, Bangalore',
    latitude: 12.9352,
    longitude: 77.6245,
    notes: 'Fresh vegetarian biryani meal boxes packed after a cancelled lunch order.',
    is_vegetarian: true,
    status: 'open',
    accepted_by_ngo_id: null,
    created_at: hoursAgo(1.5),
    photo_url: samplePhotos.biryani,
  },
  {
    id: donationIds.pastries,
    donor_id: ids.donors.indiranagar,
    title: '18 Assorted Pastries',
    category: 'bakery',
    food_type: 'Pastries',
    quantity: 18,
    unit: 'items',
    urgency: 'medium',
    prepared_at: hoursAgo(3),
    expires_at: hoursFromNow(8),
    pickup_start: hoursFromNow(1),
    pickup_end: hoursFromNow(3),
    location_name: 'Indiranagar Bakery House, 100 Feet Road, Indiranagar, Bangalore',
    latitude: 12.9784,
    longitude: 77.6408,
    notes: 'Assorted eggless and regular pastries from the morning batch.',
    is_vegetarian: true,
    status: 'open',
    accepted_by_ngo_id: null,
    created_at: hoursAgo(3),
    photo_url: samplePhotos.pastries,
  },
  {
    id: donationIds.fruitCups,
    donor_id: ids.donors.hsr,
    title: '22 Fruit Salad Cups',
    category: 'fresh_produce',
    food_type: 'Fruit salad',
    quantity: 22,
    unit: 'cups',
    urgency: 'low',
    prepared_at: hoursAgo(2),
    expires_at: hoursFromNow(10),
    pickup_start: hoursFromNow(2),
    pickup_end: hoursFromNow(5),
    location_name: 'HSR Fresh Foods, Sector 2, HSR Layout, Bangalore',
    latitude: 12.9121,
    longitude: 77.6446,
    notes: 'Sealed fruit cups with watermelon, papaya, banana, and grapes.',
    is_vegetarian: true,
    status: 'open',
    accepted_by_ngo_id: null,
    created_at: hoursAgo(2),
    photo_url: samplePhotos.fruit,
  },
  {
    id: donationIds.lunchPacks,
    donor_id: ids.donors.whitefield,
    title: '40 Corporate Lunch Packs',
    category: 'packaged',
    food_type: 'Corporate lunch packs',
    quantity: 40,
    unit: 'packs',
    urgency: 'medium',
    prepared_at: hoursAgo(4),
    expires_at: hoursFromNow(4),
    pickup_start: hoursAgo(0.5),
    pickup_end: hoursFromNow(1.5),
    location_name: 'Whitefield Tech Park Canteen, ITPL Main Road, Whitefield, Bangalore',
    latitude: 12.9698,
    longitude: 77.7500,
    notes: 'Packed rice, dal, vegetables, and curd from a reduced-attendance office lunch.',
    is_vegetarian: true,
    status: 'accepted',
    accepted_by_ngo_id: ids.ngos.communityMeals,
    created_at: hoursAgo(4),
    photo_url: samplePhotos.lunch,
  },
  {
    id: donationIds.juiceBottles,
    donor_id: ids.donors.mgRoad,
    title: '12 Juice Bottles',
    category: 'beverages',
    food_type: 'Fresh juice',
    quantity: 12,
    unit: 'bottles',
    urgency: 'medium',
    prepared_at: hoursAgo(2.5),
    expires_at: hoursFromNow(6),
    pickup_start: hoursAgo(1),
    pickup_end: hoursFromNow(1),
    location_name: 'MG Road Cafe, Church Street, MG Road, Bangalore',
    latitude: 12.9758,
    longitude: 77.6068,
    notes: 'Sealed orange and watermelon juice bottles from the evening batch.',
    is_vegetarian: true,
    status: 'in_transit',
    accepted_by_ngo_id: ids.ngos.reliefTrust,
    created_at: hoursAgo(2.5),
    photo_url: samplePhotos.beverages,
  },
  {
    id: donationIds.paneer,
    donor_id: ids.donors.jayanagar,
    title: '25 Paneer Butter Masala Portions',
    category: 'cooked_meals',
    food_type: 'Paneer curry',
    quantity: 25,
    unit: 'portions',
    urgency: 'medium',
    prepared_at: hoursAgo(23),
    expires_at: hoursFromNow(2),
    pickup_start: hoursAgo(22.5),
    pickup_end: hoursAgo(22),
    location_name: 'Jayanagar Event Caterers, 4th Block, Jayanagar, Bangalore',
    latitude: 12.9250,
    longitude: 77.5938,
    notes: 'Delivered from a small family function. Vegetarian curry packed in containers.',
    is_vegetarian: true,
    status: 'delivered',
    accepted_by_ngo_id: ids.ngos.annadaan,
    created_at: hoursAgo(23),
    photo_url: samplePhotos.lunch,
  },
  {
    id: donationIds.sandwiches,
    donor_id: ids.donors.electronicCity,
    title: '30 Mixed Veg Sandwiches',
    category: 'packaged',
    food_type: 'Vegetable sandwiches',
    quantity: 30,
    unit: 'sandwiches',
    urgency: 'medium',
    prepared_at: hoursAgo(3.5),
    expires_at: hoursFromNow(5),
    pickup_start: hoursFromNow(0.5),
    pickup_end: hoursFromNow(2),
    location_name: 'Electronic City Corporate Kitchen, Phase 1, Electronic City, Bangalore',
    latitude: 12.8452,
    longitude: 77.6602,
    notes: 'Individually wrapped veg sandwiches from a corporate training event.',
    is_vegetarian: true,
    status: 'pickup_assigned',
    accepted_by_ngo_id: ids.ngos.helpingHands,
    created_at: hoursAgo(3.5),
    photo_url: samplePhotos.sandwiches,
  },
  {
    id: donationIds.idliVada,
    donor_id: ids.donors.malleshwaram,
    title: '15 Idli Vada Breakfast Packs',
    category: 'cooked_meals',
    food_type: 'Breakfast packs',
    quantity: 15,
    unit: 'packs',
    urgency: 'low',
    prepared_at: hoursAgo(1),
    expires_at: hoursFromNow(4),
    pickup_start: hoursFromNow(0.5),
    pickup_end: hoursFromNow(2.5),
    location_name: 'Malleshwaram Tiffin Centre, 8th Cross, Malleshwaram, Bangalore',
    latitude: 13.0031,
    longitude: 77.5643,
    notes: 'Idli, vada, and chutney breakfast packs. Best consumed today.',
    is_vegetarian: true,
    status: 'open',
    accepted_by_ngo_id: null,
    created_at: hoursAgo(1),
    photo_url: samplePhotos.breakfast,
  },
  {
    id: donationIds.cancelled,
    donor_id: ids.donors.koramangala,
    title: '10 Lemon Rice Packs',
    category: 'cooked_meals',
    food_type: 'Lemon rice',
    quantity: 10,
    unit: 'packs',
    urgency: 'low',
    prepared_at: hoursAgo(23),
    expires_at: hoursAgo(20),
    pickup_start: hoursAgo(23),
    pickup_end: hoursAgo(22.5),
    location_name: 'Koramangala Kitchen, 4th Block, Koramangala, Bangalore',
    latitude: 12.9352,
    longitude: 77.6245,
    notes: 'Cancelled during demo reset because pickup window expired.',
    is_vegetarian: true,
    status: 'cancelled',
    accepted_by_ngo_id: null,
    created_at: hoursAgo(23),
    photo_url: null,
  },
  {
    id: donationIds.templeMeals,
    donor_id: ids.donors.jpNagar,
    title: '28 Temple Lunch Servings',
    category: 'cooked_meals',
    food_type: 'Rice sambar lunch',
    quantity: 28,
    unit: 'servings',
    urgency: 'high',
    prepared_at: hoursAgo(0.75),
    expires_at: hoursFromNow(3),
    pickup_start: hoursFromNow(0.25),
    pickup_end: hoursFromNow(1.25),
    location_name: 'JP Nagar Community Kitchen, 2nd Phase, JP Nagar, Bangalore',
    latitude: 12.9063,
    longitude: 77.5857,
    notes: 'Freshly packed vegetarian rice and sambar servings from community lunch.',
    is_vegetarian: true,
    status: 'open',
    accepted_by_ngo_id: null,
    created_at: hoursAgo(0.75),
    photo_url: samplePhotos.lunch,
  },
  {
    id: donationIds.snackBoxes,
    donor_id: ids.donors.marathahalli,
    title: '36 Office Snack Boxes',
    category: 'packaged',
    food_type: 'Snack boxes',
    quantity: 36,
    unit: 'boxes',
    urgency: 'medium',
    prepared_at: hoursAgo(2),
    expires_at: hoursFromNow(7),
    pickup_start: hoursFromNow(1.5),
    pickup_end: hoursFromNow(4),
    location_name: 'Marathahalli Office Pantry, Outer Ring Road, Marathahalli, Bangalore',
    latitude: 12.9569,
    longitude: 77.7011,
    notes: 'Sealed snack boxes with poha, banana, and juice from a training session.',
    is_vegetarian: true,
    status: 'open',
    accepted_by_ngo_id: null,
    created_at: hoursAgo(2),
    photo_url: samplePhotos.lunch,
  },
  {
    id: donationIds.dinnerTrays,
    donor_id: ids.donors.hebbal,
    title: '32 Hostel Dinner Trays',
    category: 'cooked_meals',
    food_type: 'Dinner trays',
    quantity: 32,
    unit: 'trays',
    urgency: 'high',
    prepared_at: hoursAgo(2.25),
    expires_at: hoursFromNow(3),
    pickup_start: hoursFromNow(0.5),
    pickup_end: hoursFromNow(2),
    location_name: 'Hebbal Hostel Mess, Kempapura Main Road, Hebbal, Bangalore',
    latitude: 13.0358,
    longitude: 77.5970,
    notes: 'Chapati, veg curry, and rice trays packed for quick pickup.',
    is_vegetarian: true,
    status: 'pickup_assigned',
    accepted_by_ngo_id: ids.ngos.hopeShelter,
    created_at: hoursAgo(2.25),
    photo_url: samplePhotos.lunch,
  },
  {
    id: donationIds.breadLoaves,
    donor_id: ids.donors.koramangala,
    title: '24 Whole Wheat Bread Loaves',
    category: 'bakery',
    food_type: 'Bread loaves',
    quantity: 24,
    unit: 'loaves',
    urgency: 'low',
    prepared_at: hoursAgo(5),
    expires_at: hoursFromNow(12),
    pickup_start: hoursFromNow(3),
    pickup_end: hoursFromNow(6),
    location_name: 'Koramangala Kitchen, 4th Block, Koramangala, Bangalore',
    latitude: 12.9352,
    longitude: 77.6245,
    notes: 'Fresh bread loaves from morning prep, packed in bakery sleeves.',
    is_vegetarian: true,
    status: 'open',
    accepted_by_ngo_id: null,
    created_at: hoursAgo(5),
    photo_url: samplePhotos.pastries,
  },
  {
    id: donationIds.dosaPacks,
    donor_id: ids.donors.whitefield,
    title: '45 Dosa Breakfast Packs',
    category: 'cooked_meals',
    food_type: 'Dosa breakfast packs',
    quantity: 45,
    unit: 'packs',
    urgency: 'medium',
    prepared_at: daysAgo(0.8),
    expires_at: hoursAgo(10),
    pickup_start: daysAgo(0.8),
    pickup_end: daysAgo(0.7),
    location_name: 'Whitefield Tech Park Canteen, ITPL Main Road, Whitefield, Bangalore',
    latitude: 12.9698,
    longitude: 77.7500,
    notes: 'Delivered breakfast packs from a morning office event.',
    is_vegetarian: true,
    status: 'delivered',
    accepted_by_ngo_id: ids.ngos.communityMeals,
    created_at: daysAgo(0.8),
    photo_url: samplePhotos.breakfast,
  },
  {
    id: donationIds.coffeeFlasks,
    donor_id: ids.donors.indiranagar,
    title: '8 Filter Coffee Flasks',
    category: 'beverages',
    food_type: 'Filter coffee',
    quantity: 8,
    unit: 'flasks',
    urgency: 'low',
    prepared_at: hoursAgo(23),
    expires_at: hoursAgo(20),
    pickup_start: hoursAgo(23),
    pickup_end: hoursAgo(22.5),
    location_name: 'Indiranagar Bakery House, 100 Feet Road, Indiranagar, Bangalore',
    latitude: 12.9784,
    longitude: 77.6408,
    notes: 'Cancelled because pickup was no longer needed after a demo reset.',
    is_vegetarian: true,
    status: 'cancelled',
    accepted_by_ngo_id: null,
    created_at: hoursAgo(23),
    photo_url: null,
  },
];

const seedMatchSuggestions = [
  { id: '99990000-0000-0000-0000-000000000001', donation_id: donationIds.vegBiryani, ngo_id: ids.ngos.reliefTrust, score: 96, reason: 'Strong Bangalore match: urgent cooked meals, high capacity, and reliable response from JP Nagar.', rank: 1 },
  { id: '99990000-0000-0000-0000-000000000002', donation_id: donationIds.vegBiryani, ngo_id: ids.ngos.annadaan, score: 91, reason: 'Good nearby option in Jayanagar with cooked meal capacity.', rank: 2 },
  { id: '99990000-0000-0000-0000-000000000003', donation_id: donationIds.pastries, ngo_id: ids.ngos.helpingHands, score: 88, reason: 'Accepts bakery items and is close to Indiranagar via HSR Layout.', rank: 1 },
  { id: '99990000-0000-0000-0000-000000000004', donation_id: donationIds.pastries, ngo_id: ids.ngos.reliefTrust, score: 84, reason: 'High capacity and bakery support for same-day pickup.', rank: 2 },
  { id: '99990000-0000-0000-0000-000000000005', donation_id: donationIds.fruitCups, ngo_id: ids.ngos.hopeShelter, score: 82, reason: 'Fresh produce support and available afternoon capacity.', rank: 1 },
  { id: '99990000-0000-0000-0000-000000000006', donation_id: donationIds.fruitCups, ngo_id: ids.ngos.annadaan, score: 80, reason: 'Good vegetarian food fit and reasonable pickup distance.', rank: 2 },
  { id: '99990000-0000-0000-0000-000000000007', donation_id: donationIds.idliVada, ngo_id: ids.ngos.annadaan, score: 93, reason: 'Breakfast packs fit the Jayanagar meal program and can be collected quickly.', rank: 1 },
  { id: '99990000-0000-0000-0000-000000000008', donation_id: donationIds.idliVada, ngo_id: ids.ngos.reliefTrust, score: 86, reason: 'High capacity for cooked meal packs with reliable response.', rank: 2 },
  { id: '99990000-0000-0000-0000-000000000009', donation_id: donationIds.templeMeals, ngo_id: ids.ngos.reliefTrust, score: 97, reason: 'Urgent cooked meals near JP Nagar with strong capacity and fast response.', rank: 1 },
  { id: '99990000-0000-0000-0000-000000000010', donation_id: donationIds.templeMeals, ngo_id: ids.ngos.annadaan, score: 92, reason: 'Cooked meal fit and close Jayanagar distribution route.', rank: 2 },
  { id: '99990000-0000-0000-0000-000000000011', donation_id: donationIds.snackBoxes, ngo_id: ids.ngos.communityMeals, score: 90, reason: 'Packaged food near Marathahalli with good afternoon capacity.', rank: 1 },
  { id: '99990000-0000-0000-0000-000000000012', donation_id: donationIds.snackBoxes, ngo_id: ids.ngos.hopeShelter, score: 78, reason: 'Packaged snack boxes fit shelter evening service.', rank: 2 },
  { id: '99990000-0000-0000-0000-000000000013', donation_id: donationIds.breadLoaves, ngo_id: ids.ngos.reliefTrust, score: 85, reason: 'Bakery support and flexible same-day pickup capacity.', rank: 1 },
  { id: '99990000-0000-0000-0000-000000000014', donation_id: donationIds.breadLoaves, ngo_id: ids.ngos.helpingHands, score: 82, reason: 'Bakery item support and practical Koramangala to HSR route.', rank: 2 },
];

const seedDeliveryJobs = [
  {
    id: jobIds.lunchPacks,
    donation_id: donationIds.lunchPacks,
    donor_id: ids.donors.whitefield,
    ngo_id: ids.ngos.communityMeals,
    delivery_partner_id: ids.delivery,
    pickup_address: 'Whitefield Tech Park Canteen, ITPL Main Road, Whitefield, Bangalore',
    drop_address: 'Community Meals Foundation, Marathahalli, Bangalore',
    eta_minutes: 24,
    distance_km: 7.4,
    status: 'assigned',
    donation_title: '40 Corporate Lunch Packs',
    created_at: hoursAgo(3.5),
    updated_at: hoursAgo(3.5),
  },
  {
    id: jobIds.juiceBottles,
    donation_id: donationIds.juiceBottles,
    donor_id: ids.donors.mgRoad,
    ngo_id: ids.ngos.reliefTrust,
    delivery_partner_id: ids.delivery,
    pickup_address: 'MG Road Cafe, Church Street, MG Road, Bangalore',
    drop_address: 'Bengaluru Food Relief Trust, JP Nagar, Bangalore',
    eta_minutes: 20,
    distance_km: 8.1,
    status: 'in_transit',
    donation_title: '12 Juice Bottles',
    created_at: hoursAgo(2),
    updated_at: hoursAgo(0.5),
  },
  {
    id: jobIds.paneer,
    donation_id: donationIds.paneer,
    donor_id: ids.donors.jayanagar,
    ngo_id: ids.ngos.annadaan,
    delivery_partner_id: ids.delivery,
    pickup_address: 'Jayanagar Event Caterers, 4th Block, Jayanagar, Bangalore',
    drop_address: 'Annadaan Bengaluru, Jayanagar, Bangalore',
    eta_minutes: 14,
    distance_km: 2.6,
    status: 'delivered',
    donation_title: '25 Paneer Butter Masala Portions',
    created_at: daysAgo(1),
    updated_at: hoursAgo(18),
  },
  {
    id: jobIds.sandwiches,
    donation_id: donationIds.sandwiches,
    donor_id: ids.donors.electronicCity,
    ngo_id: ids.ngos.helpingHands,
    delivery_partner_id: ids.delivery,
    pickup_address: 'Electronic City Corporate Kitchen, Phase 1, Electronic City, Bangalore',
    drop_address: 'Helping Hands Bangalore, HSR Layout, Bangalore',
    eta_minutes: 28,
    distance_km: 10.3,
    status: 'assigned',
    donation_title: '30 Mixed Veg Sandwiches',
    created_at: hoursAgo(3),
    updated_at: hoursAgo(3),
  },
  {
    id: jobIds.dinnerTrays,
    donation_id: donationIds.dinnerTrays,
    donor_id: ids.donors.hebbal,
    ngo_id: ids.ngos.hopeShelter,
    delivery_partner_id: ids.delivery,
    pickup_address: 'Hebbal Hostel Mess, Kempapura Main Road, Hebbal, Bangalore',
    drop_address: 'Hope Shelter Network, Hebbal, Bangalore',
    eta_minutes: 12,
    distance_km: 3.1,
    status: 'accepted',
    donation_title: '32 Hostel Dinner Trays',
    created_at: hoursAgo(2),
    updated_at: hoursAgo(1.75),
  },
  {
    id: jobIds.dosaPacks,
    donation_id: donationIds.dosaPacks,
    donor_id: ids.donors.whitefield,
    ngo_id: ids.ngos.communityMeals,
    delivery_partner_id: ids.delivery,
    pickup_address: 'Whitefield Tech Park Canteen, ITPL Main Road, Whitefield, Bangalore',
    drop_address: 'Community Meals Foundation, Marathahalli, Bangalore',
    eta_minutes: 26,
    distance_km: 7.4,
    status: 'delivered',
    donation_title: '45 Dosa Breakfast Packs',
    created_at: daysAgo(0.8),
    updated_at: hoursAgo(11),
  },
];

const analyticsProfiles = [
  { ngoId: ids.ngos.reliefTrust, offset: 0, summary: 'Bangalore demo data: Koramangala, JP Nagar, and Malleshwaram are active donation areas this week.' },
  { ngoId: ids.ngos.communityMeals, offset: 1, summary: 'Bangalore demo data: Whitefield and Marathahalli are creating strong office lunch demand.' },
  { ngoId: ids.ngos.helpingHands, offset: 2, summary: 'Bangalore demo data: Electronic City and HSR Layout are active for packaged meal pickups.' },
];

const seedAnalytics = analyticsProfiles.flatMap((profile, profileIndex) => {
  const categories = ['cooked_meals', 'bakery', 'fresh_produce', 'packaged'];
  return Array.from({ length: 14 }, (_, i) => ({
    id: `77770000-0000-0000-${String(profileIndex + 1).padStart(4, '0')}-${String(i + 1).padStart(12, '0')}`,
    ngo_id: profile.ngoId,
    date: daysAgo(13 - i),
    donations_received: [2, 3, 4, 3, 5, 4, 6, 3, 4, 5, 4, 6, 5, 7][i] + profile.offset,
    meals_rescued: [45, 62, 80, 58, 95, 76, 110, 64, 82, 105, 92, 120, 108, 132][i] + profile.offset * 12,
    avg_acceptance_time: [14, 13, 12, 15, 11, 12, 10, 14, 13, 11, 10, 9, 10, 8][i] + profile.offset,
    top_category: categories[(i + profile.offset) % categories.length],
    summary_text: profile.summary,
  }));
});

async function deleteByIds(table, column, values) {
  if (!values.length) return;
  const { error } = await supabase.from(table).delete().in(column, values);
  if (error) throw new Error(`Failed deleting ${table}: ${error.message}`);
}

async function getExistingDemoDonationIds() {
  const { data, error } = await supabase
    .from('donations')
    .select('id, donor_id, accepted_by_ngo_id, title');

  if (error) throw new Error(`Failed reading donations: ${error.message}`);

  const userIds = new Set(demoDonationOwnerIds);
  return (data || [])
    .filter((row) => userIds.has(row.donor_id) || userIds.has(row.accepted_by_ngo_id) || row.title?.startsWith('Phase 1 Workflow Test'))
    .map((row) => row.id);
}

async function getExistingDemoJobIds(donationIdsToDelete) {
  const { data, error } = await supabase
    .from('delivery_jobs')
    .select('id, donation_id, donor_id, ngo_id, delivery_partner_id');

  if (error) throw new Error(`Failed reading delivery jobs: ${error.message}`);

  const userIds = new Set(demoDonationOwnerIds);
  const donationSet = new Set(donationIdsToDelete);
  return (data || [])
    .filter((row) => donationSet.has(row.donation_id) || userIds.has(row.donor_id) || userIds.has(row.ngo_id) || userIds.has(row.delivery_partner_id))
    .map((row) => row.id);
}

async function resetDemoData() {
  console.log('Resetting demo-only Supabase rows...');
  const existingDonationIds = await getExistingDemoDonationIds();
  const existingJobIds = await getExistingDemoJobIds(existingDonationIds);

  await deleteByIds('match_suggestions', 'donation_id', existingDonationIds);
  await deleteByIds('delivery_jobs', 'id', existingJobIds);
  await deleteByIds('analytics_snapshots', 'ngo_id', Object.values(ids.ngos));
  await deleteByIds('donations', 'id', existingDonationIds);
  await deleteByIds('ngo_profiles', 'user_id', Object.values(ids.ngos));
  await deleteByIds('profiles', 'id', demoUserIds);
}

async function upsert(table, rows) {
  const { error } = await supabase.from(table).upsert(rows);
  if (error) throw new Error(`Failed seeding ${table}: ${error.message}`);
  console.log(`Seeded ${table}: ${rows.length}`);
}

async function seed() {
  await resetDemoData();
  await upsert('profiles', seedUsers);
  await upsert('ngo_profiles', seedNGOProfiles);
  await upsert('donations', seedDonations);
  await upsert('match_suggestions', seedMatchSuggestions);
  await upsert('delivery_jobs', seedDeliveryJobs);
  await upsert('analytics_snapshots', seedAnalytics);
  console.log('Bangalore demo reseed complete.');
}

seed().catch((error) => {
  console.error(error.message || error);
  process.exit(1);
});
